# Generated by Django 5.1.2 on 2024-10-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
    ]
